### ISSUE TITLE
Suggestion: Combine player kills into a single category

### ISSUE THREAD

**Issue by OlavH96** [TheStonedTurtle/Loot-Logger#10]
Very nice plugin! Love it for bosses, however I think it would be nice to have player kills as an individual category like bosses are. It currently tracks player kills, however each player becomes its own category, which is not very helpful.

Pictures, current behaviour.

![Screenshot from 2020-03-24 00-46-00](https://user-images.githubusercontent.com/14239681/77373561-e1c48300-6d68-11ea-8deb-1ef1e7fd3762.png)
![Screenshot from 2020-03-24 00-46-10](https://user-images.githubusercontent.com/14239681/77373569-e4bf7380-6d68-11ea-86bc-55b686404187.png)

Desired outcome, like above image, except every player kill instead of just for this player.

Keep up the good work!

**Comment by TheStonedTurtle** [comment]
Due to the way data is stored the only way to filter by category (PvM vs PvP) would require reading data from each file on load. Adding this would require rewriting the data storage to use a folders for each event type, which would also require writing a migration tool for existing data.

If you have any suggestions for how the UI should show these different categories let me know.

**Comment by OlavH96** [comment]
I envision the UI could look something like this, with space for different categories.

![Screenshot from 2020-0ssds3-24 17-28-42](https://user-images.githubusercontent.com/14239681/77452343-24806c80-6df6-11ea-8b54-efc4abacd473.png)

I see your log files contain the type: "PLAYER" for player kills, which could be used to migrate these files.

My ad hoc solution would be to load every file when above PvP button is clicked, and keep every file with type: PLAYER in it. Combining the result and passing it to the existing LootPanel UI. I am not very experienced in Runelite development, so I am not sure if this is doable for you.

**Comment by TheStonedTurtle** [comment]
So i created a system to separate loot by Record Type but now IDK how to display the different categories.

There are events (Like COX, TOB, Barrows, Gauntlet, Herbiboar, etc), pickpockets, NPCs, players, and unknown. I don't think an icon for each category would be a good idea (like your mock up) as those icons are tied to a config option.

Do you think separating them with collapse-able headers below the search bar would be sufficient?
