### ISSUE TITLE
Doesn't track one of my accounts.

### ISSUE THREAD

**Issue by mattbrady177** [TheStonedTurtle/Loot-Logger#12]
I have 5 accounts.
The loot logger perfectly tracks all of them expect for one of them for some odd reason
I'm signed into runelite 
I have loot logger enabled.
I tried to delete it and redownload.
Nothing works it won't track items on one account for some reason.
But for all the others it does.
Do you know why this might be happening and how I can fix it?

**Comment by TheStonedTurtle** [comment]
Can you send me the log file for your client and also check if theres a folder for your username under `C:\Users\**NAME**\.runelite\loots\`.

The log file would be under `.runelite\logs` and it would be called `client.log`

**Comment by mattbrady177** [comment]
I checked and there is a folder for all of my accounts including the one that isn't working it might still be tracking but ingame client won't open or show them.

[client.log](https://github.com/TheStonedTurtle/Loot-Logger/files/4433074/client.log)

**Comment by TheStonedTurtle** [comment]
It looks like one (or more) of the loot files aren't in the valid format, Can you zip the folder for the account that's having issues?

**Comment by TheStonedTurtle** [comment]
Example Gif:
![vGs1BZlmgN](https://user-images.githubusercontent.com/29030969/78500058-3a9cff80-7709-11ea-9b4a-13af9232dfce.gif)

**Comment by mattbrady177** [comment]
Yes I zipped the folder and it still didn't work. But now i got it working. Since it wasn't tracking at all for some reason I just went into .runelite loots and deleted the entire profile for the account and now it seems to track correctly.

**Comment by mattbrady177** [comment]
Is there anyway to reset loot without deleting it permenately? For example killed 250 rune dragons yesterday want to reset it for today. Noticed refresh panel doesn't do nothing?

**Comment by TheStonedTurtle** [comment]
You can send me that zip folder so i can fix your data

Theres an issue i cant reproduce where instead of each entry being on its
own line two entires will be on the same line with a bunch of spaces
between them. This is most likely the issue you ran into.

**Comment by mattbrady177** [comment]
It's working now but can't reset kills logged for the day?

**Comment by TheStonedTurtle** [comment]
> It's working now but can't reset kills logged for the day?

Not sure what you are asking here, if you want to delete the tracked loot use the trash icon (which deletes the file from your computer). If you only want to delete partial data you'd have to manually edit the file and remove those entries.

If you are asking for some sort of Session view where it just shows data from the current client session then that'd be a feature request, and probably better suited for the RL Loot Tracker.

**Comment by mattbrady177** [comment]
Okay thanks man. It's all working perfect now. Will close and you can mark as solved!
