### ISSUE TITLE
Double entries on UI after reopening & getting a new entry

### ISSUE THREAD

**Issue by ThatJustin** [TheStonedTurtle/Loot-Logger#16]
So, the live kills are logged with a capitalized name, but then it is saved in all lowercase locally, so there would be two entries if you loaded a previous log and added onto it.

Just a minor thing really. 

![](https://i.imgur.com/9CZBYB7.png)

**Comment by TheStonedTurtle** [comment]
This should be fixed in v2.2.1 of the plugin
