### ISSUE TITLE
Pet(s) do not track correctly

### ISSUE THREAD

**Issue by SieBrum** [TheStonedTurtle/Loot-Logger#18]
![image](https://user-images.githubusercontent.com/14212955/89888268-fa2a2280-dbcf-11ea-8087-10ca6d433e02.png)

Not sure if known, but pets do not seem to be tracked (although they are a visible unique on the loot logger panel. 
As shown in screenshot. Received pet but it was not logged in the top-part of the loot logger panel (image still grey)

**Comment by TheStonedTurtle** [comment]
Yeah, I just recently re-added pet support  in version 2.2 of the plugin. You can check your version by looking the plugin-hub panel, if its not v2.2 then I'm going to close this. If it is v2.2 let me know so I can troubleshoot.

You can manually add your pet by adding the below snippet into your `drops` entry for that kill.

`,{"name":"Pet snakeling","id":12921,"quantity":1,"price":0}`

Your entry should look something like this:
`{"name":"Zulrah","level":725,"killCount":26,"type":"NPC","drops": [{"name": "Zulrah's scales", "id": 12934, "quantity": 185, "price": 221}]}`

You want to make sure you add it between the `}` and `]}`, like so:

`{"name":"Zulrah","level":725,"killCount":26,"type":"NPC","drops": [{"name": "Zulrah's scales", "id": 12934, "quantity": 185, "price": 221}]},{"name":"Pet snakeling","id":12921,"quantity":1,"price":0}`

You can find this file at `~/.runelite/loots/npc/zulrah.log` where `~` is your home directory (`C:\Users\Name\`)

**Comment by SieBrum** [comment]
![image](https://user-images.githubusercontent.com/14212955/89890019-e59b5980-dbd2-11ea-9021-68a90079c301.png)
version seems to be correct. Thanks for the manual line though, will add it.

**Comment by TheStonedTurtle** [comment]
This should be fixed in version 2.2.1 of the plugin. The text checks were missing the ending punctuation. Thanks for your help 👍
