### ISSUE TITLE
Loot Logger suddenly not Logging drops

### ISSUE THREAD

**Issue by bmwaze** [TheStonedTurtle/Loot-Logger#36]
So this issue started yesterday, 2 days ago I was minding my business doing slayer and clue scrolls. went to bed and the day after, the plugin stopped logging loots anymore, I didnt name change, I didnt edit any settings. It just stopped working.

**Comment by TheStonedTurtle** [comment]
Is the Runelite Loot Tracker enabled? If it's disabled this plugin wont work.

If it is enabled does it not log anything or just specific stuff?

**Comment by bmwaze** [comment]
Oh no it is definitely enabled, I never turned it off after installing. It doesn't log anything at all. Current session data is always empty, boss logs dont update etc.
Ive tried restarting Runelite, I tried reinstalling the plugin. Nothing seems to work. 
Like I said above, I havent changed any settings since installing the plugin so im really confused as to why it stopped logging.

**Comment by TheStonedTurtle** [comment]
Can you check for any errors in your `%USERPROFILE%/.runelite/logs/client.log`  or upload that file here.

**Comment by bmwaze** [comment]
Oh wait a second.. Loot Tracker plugin has to be active for Loot Logger to work?

**Comment by TheStonedTurtle** [comment]
> Oh wait a second.. Loot Tracker plugin has to be active for Loot Logger to work?

Yeah this plugin just logs the data the Loot Tracker provides locally. It does a few extra things like track KC and attempt to track pets.

![image](https://user-images.githubusercontent.com/29030969/174326660-08c37b9d-2e83-4a8d-9348-44d122cd8f50.png)
