### ISSUE TITLE
Loot logger not loading boss logs properly

### ISSUE THREAD

**Issue by scssquatch** [TheStonedTurtle/Loot-Logger#38]
Getting this error all over my client.log. I'm not sure if I need to update something, but it's causing the plugin to not load any NPC.
`Caused by: java.text.ParseException: Failed to parse date ["Jan 3, 2022, 8:21:06 PM"]: Invalid number: Jan `

**Comment by scssquatch** [comment]
`{"name":"Vorkath","level":732,"killCount":1,"type":"NPC","drops":[{"name":"Superior dragon bones","id":22124,"quantity":1,"price":12876},{"name":"Superior dragon bones","id":22124,"quantity":1,"price":12876},{"name":"Blue dragonhide","id":1751,"quantity":1,"price":1809},{"name":"Blue dragonhide","id":1751,"quantity":1,"price":1809},{"name":"Dragon arrowtips","id":11237,"quantity":43,"price":1930},{"name":"Dragon plateskirt","id":4585,"quantity":1,"price":161153}],"date":"Apr 12, 2022, 8:09:27 PM"}` That's one of the lines in question, not sure if some formatting got broken/changed

**Comment by TheStonedTurtle** [comment]
Try downloading the latest version of the RuneLite launcher from the official website, you may be using an outdated launcher. You can see the launcher version in the `info tab`. I'm on `2.2.0` but I think anything over v2 should be fine.

![image](https://user-images.githubusercontent.com/29030969/178160918-148c6727-91b4-43a6-b12c-d0a17c31c98f.png)

**Comment by scssquatch** [comment]
That worked! Thank you!
