### ISSUE TITLE
The Loot Logger plugin saves in another folder when using the Jagex Launcher

### ISSUE THREAD

**Issue by Lorentary** [TheStonedTurtle/Loot-Logger#41]
The "npc", "events", "pickpockets" etc folders appear in the root "Loots" folder instead of "Loots\ACCOUNT_NAME".

Hence, if the account in the Jagex Launcher is changed the loot logs would become mixed.

**Comment by TheStonedTurtle** [comment]
Fixed in aa29c3a9193bbed97775cb787c049fb61179ed30

**Comment by Lorentary** [comment]
Now loot is saved in a folder which is just a seemingly random string of numbers
