### ISSUE TITLE
READ IF MISSING DATA - Loot logger created new profiles for an account I have used before

### ISSUE THREAD

**Issue by turkeymana** [TheStonedTurtle/Loot-Logger#44]
Inside the RL folder it created a new profile with a large 19 digit negative integer. This is making it not recognize that the account I'm logged into already has a folder and thus is creating two files for the same account. Not sure as to why or how this happened.

**Comment by TheStonedTurtle** [comment]
The plugin should have renamed your account folder to the one with the numbers. The Jagex launcher does not have access to your login name so I changed the plugin to use your accounthash as the folder name so the plugin would work regardless of how you launched it.

Copy the number folder name (your account hash) and then rename the folder with your login name to that. You may want to delete the one with numbers first or rename it so it doesn't try to overwrite files.

**Comment by TheStonedTurtle** [comment]
I found out this issue only existed if your hash was negative, a fix has been pushed out but will only affect people moving forward with the conversion. You will still need to follow the above steps.

**Comment by turkeymana** [comment]
Thank you. always happy to bug hunt :)

**Comment by TheStonedTurtle** [comment]
Re-opening so others who have a similar issue can find this

**Comment by TheStonedTurtle** [comment]
If someone has this problem that means they haven't played in over 1.5years, as such I'm closing & unpinning as this issue.
