### ISSUE TITLE
All data is missing

### ISSUE THREAD

**Issue by Insonia-1** [TheStonedTurtle/Loot-Logger#45]
Hi, since today's update all my data is gone from runelite. I haven't logged out from runelite and im still using the same account but no info in there. I've check runelite website and the information about the loot is there just doesnt show when I open runelite.

Is there anyway to update the information? 

Thank you
![runelite](https://user-images.githubusercontent.com/113558771/190267717-9d3982b8-6423-4c0a-8b05-3d15f51beb68.jpg)
![runelite site](https://user-images.githubusercontent.com/113558771/190267721-e7609091-9515-407b-85f7-3f782f352ae1.jpg)

**Comment by Insonia-1** [comment]
You can ignore this. Found the solution on another person report. Had to do with the new folder being a negative hash. Solved :)

**Comment by TheStonedTurtle** [comment]
Yeah an unfortunate assumption on my end caused this issue, sorry about that
