### ISSUE TITLE
Dorgesh-Kaan Chest Loot on the Ground Causes Duplicate Log Entries

### ISSUE THREAD

**Issue by trey-d** [TheStonedTurtle/Loot-Logger#54]
When looting Dorgesh-Kaan Chests with a full inventory, loot is placed on the ground. I believe the loot behaves like random event drops in that it follows you with world hops. When hopping a world with loot on the ground, the Loot Logger sees this as a repeat loot and adds it to the log every world hop.

**Comment by TheStonedTurtle** [comment]
This plugin does do not do any loot processing, all it does is subscribe to the RuneLite loot events and log them into local files. The side-panel UI is just a way to view this stored data.

I'd recommend creating this issue on the RuneLite github.
