### ISSUE TITLE
Can't view total loot from an NPC

### ISSUE THREAD

**Issue by Hentiny** [TheStonedTurtle/Loot-Logger#59]
I'm assuming it's due to the large file size (9500 KB from roughly 60000+ ammonite crabs killed) but I'm unable to view the total loot from all my crab slaying in the Loot Logger sidebar. Any attempt to open that specific NPC freezes the sidebar for a few seconds then everything in the search bar disappears. The plugin is still actively adding kills to the local file so that's not an issue.

**Comment by TheStonedTurtle** [comment]
For some reason which I have been unable to pinpoint the log files sometimes end up with two entries being written to the same line. This is most likely the cause of the issue you are seeing.

The best way to find this is to search for `}\s*{` with `regex` support. the `\s*` means as many, or few, spaces.

You can also upload the log file question here and I can search for you.

**Comment by Hentiny** [comment]
I had some massive lag spikes recently so that could've been the cause for a double up (like game freezing for 20+ seconds).

I wasn't able to find a search tool with regex support that worked either.

[ammonite crab.log](https://github.com/user-attachments/files/15986204/ammonite.crab.log)

**Comment by TheStonedTurtle** [comment]
I'm not sure how but your file had a bunch of Unicode NUL characters (<0x00>) inside it on line 36422. I've removed them and this seems to be working just fine again. 
[ammonite.crab.log](https://github.com/user-attachments/files/16039225/ammonite.crab.log)

**Comment by Hentiny** [comment]
So it looks like the power for my street went out while I was playing that day and line 36422 was the first crab I killed after the power came back.
