### ISSUE TITLE
Suggestion: Save data across multiple devices on the same Runelite account

### ISSUE THREAD

**Issue by Blondeyfox** [TheStonedTurtle/Loot-Logger#6]
As someone who plays on the same runescape account across a laptop and a PC, with the same Runelite account, it would be awesome if it were possible to sync across both. If this isn't possible, is there a way to transfer the local data over by automatically saving it in the cloud and just copying it into my runelite folder when I want to play?

**Comment by TheStonedTurtle** [comment]
Unfortunately this is an issue with local storage, and why RL went with cloud storage. There's a lot of issues with trying to not duplicate data when doing a combination of both that I just don't want to deal with. The only way to accomplish what you want currently would be to manually copy the content of files with the same name (I.E. `man.log`) into a new file and put those the the /loots/*username* directory  the UI display that.

I don't see myself addressing this so I'm going to close the issue, Sorry.
