### ISSUE TITLE
Not tracking use of runes via slayer staff (e) autocasting slayer dart

### ISSUE THREAD

**Issue by Inom11** [TheStonedTurtle/Loot-Logger#7]
Doesn't seem to be tracking death/mind runes properly when using slayer staff (e) slayer dart, Sometimes it'll track the first cast but nothing after. Works fine when I cast normally.

**Comment by TheStonedTurtle** [comment]
I believe you have the wrong plugin, i believe you are looking for https://github.com/Dyldozer/SuppliesTrackerExternal/issues. This plugin is only an extension of the Loot Tracker and stores data locally and by username.
